FROM ghcr.io/xlionjuan/almalinux-bootc:base@sha256:fffb0ac9bc32321540ca41175bb7956ed1c8ec080bd5dbe1737866c6faff2d07

COPY build.sh /tmp/build.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/build.sh && \
    dnf clean all && \
    rm -rf \
        /var/lib/dnf \
        /var/cache/* \
        /var/log/* \
        /var/tmp/* \
        /tmp/*

RUN bootc container lint
