FROM ghcr.io/xlionjuan/almalinux-bootc:base@sha256:502c60d752b3d295c0d8ac23b54c911a9bc97759334f4d28b6194667ce89447a

COPY build.sh /tmp/build.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/build.sh && \
    dnf clean all && \
    rm -rf \
        /var/lib/dnf \
        /var/cache/* \
        /var/log/* \
        /var/tmp/* \
        /tmp/*

RUN bootc container lint
