FROM ghcr.io/xlionjuan/almalinux-bootc:base-docker@sha256:677f3793c3dd59d752f73a08228df2c48dd62d61ff8a0f91f89d3015c86535c3

COPY build.sh /tmp/build.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/build.sh && \
    dnf clean all && \
    rm -rf /var/log/* && \
    ostree container commit

RUN bootc container lint
