FROM ghcr.io/xlionjuan/almalinux-bootc:base-arm@sha256:5780c1964ca92f0e6264451f8c17747402f3ac4b4df653be7f675c05905a976e

COPY build.sh /tmp/build.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/build.sh && \
    dnf clean all && \
    rm -rf /var/log/* && \
    ostree container commit

RUN bootc container lint
