FROM ghcr.io/xlionjuan/almalinux-bootc:base-arm@sha256:aa6469350e444898a0c7b65b2e4bfe0466835c068befa5967eab1b4c9db0169e

COPY build.sh /tmp/build.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/build.sh && \
    dnf clean all && \
    rm -rf /var/log/* && \
    ostree container commit

RUN bootc container lint
