FROM ghcr.io/xlionjuan/almalinux-bootc:base-arm@sha256:1d51401fbb8c60188a6e45bda568ed435bf73b6822b32fe50ba3f81f34a328a8

COPY build.sh /tmp/build.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/build.sh && \
    dnf clean all && \
    rm -rf /var/log/* && \
    ostree container commit

RUN bootc container lint
