FROM ghcr.io/xlionjuan/almalinux-bootc:base@sha256:80a75263204bcde18e019eb27891e3040c27c113aa81836e445b69e925f5a788

COPY build.sh /tmp/build.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/build.sh && \
    dnf clean all && \
    rm -rf /var/log/* && \
    ostree container commit

RUN bootc container lint
