FROM ghcr.io/xlionjuan/almalinux-bootc:base@sha256:6b3d63bf8a04597eeaa3ee3f494d9e1e6ce700ded6ac61c7a6f6c6b5f296c5b8

COPY build.sh /tmp/build.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/build.sh && \
    dnf clean all && \
    rm -rf /var/log/* && \
    ostree container commit

RUN bootc container lint
