FROM ghcr.io/xlionjuan/almalinux-bootc:base@sha256:1023efd2287bf03607105f305fc33dfd491491189ba8b7ebbb336cf9d6ffb9a7

COPY build.sh /tmp/build.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/build.sh && \
    dnf clean all && \
    rm -rf /var/log/* && \
    ostree container commit

RUN bootc container lint
