FROM ghcr.io/xlionjuan/almalinux-bootc:base-docker-arm@sha256:2d8a568b4c16e8cb7864e6ce61ca030bd16c09ba1056d38add43e8caa254f275

COPY build.sh /tmp/build.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/build.sh && \
    dnf clean all && \
    rm -rf /var/log/* && \
    ostree container commit

RUN bootc container lint
