FROM ghcr.io/xlionjuan/almalinux-bootc:base-docker-arm@sha256:f47303af2782a87c7b7d0b24b4d54974e847f5b4e4d0fa5be63570ca8098e827

COPY build.sh /tmp/build.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/build.sh && \
    dnf clean all && \
    rm -rf /var/log/* && \
    ostree container commit

RUN bootc container lint
