FROM ghcr.io/xlionjuan/almalinux-bootc:base-docker-arm@sha256:a54a733d337d4c4d5d498b068d55b81a22eb6788f699dad90768d07592170c6f

COPY build.sh /tmp/build.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/build.sh && \
    dnf clean all && \
    rm -rf /var/log/* && \
    ostree container commit

RUN bootc container lint
