FROM quay-oci-cache.xlion.dev/almalinuxorg/almalinux-bootc:10
# quay.io/almalinuxorg/almalinux-bootc:10

COPY build.sh /tmp/build.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/build.sh && \
    dnf clean all && \
    rm -rf /var/log/* && \
    ostree container commit

# RUN bootc container lint
