# FROM quay-oci-cache.xlion.dev/almalinuxorg/almalinux-bootc:10
FROM quay.io/almalinuxorg/almalinux-bootc:10@sha256:64a78b5d36a2ab9b9441fabb59a0429a4c395fca8908f3c420d488b6c6ef35bc

COPY build.sh /tmp/build.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/build.sh && \
    dnf clean all && \
    rm -rf \
        /var/lib/dnf \
        /var/cache/* \
        /var/log/* \
        /var/tmp/* \
        /tmp/*

RUN bootc container lint
