# FROM quay-oci-cache.xlion.dev/almalinuxorg/almalinux-bootc:10
FROM quay.io/almalinuxorg/almalinux-bootc:10@sha256:fa1fb98ddac92da38a123b39af578ff960c3f40b51cf91b92f39b537126b47d9

COPY build.sh /tmp/build.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/build.sh && \
    dnf clean all && \
    rm -rf /var/log/* && \
    ostree container commit

RUN bootc container lint
