# FROM quay-oci-cache.xlion.dev/almalinuxorg/almalinux-bootc:10
FROM quay.io/almalinuxorg/almalinux-bootc:10@sha256:fbfbb7ce472b1b183270b3b385c95f2e700208d9f905da1d8fe373a7c407932f

COPY build.sh /tmp/build.sh

RUN mkdir -p /var/lib/alternatives && \
    /tmp/build.sh && \
    dnf clean all && \
    rm -rf /var/log/* && \
    ostree container commit

RUN bootc container lint
