name: base-docker
on:
  workflow_dispatch:
  schedule:
    - cron: '40 2 * * 3'  # Runs at 02:40, only on Wednesday
  push:
    branches:
      - main
    paths:
      - 'base-docker/**'

permissions:
  contents: read
  packages: write
  # id-token: write
  # attestations: write

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    with:
      path: base-docker
      tag: base-docker
