name: base-arm
on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * 3'  # Runs at 02:30, only on Wednesday
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - 'base/**'

permissions:
  contents: read
  packages: write
  # id-token: write
  # attestations: write

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    with:
      path: base
      tag: base-arm
      runner: ubuntu-24.04-arm
