name: base-docker-arm
on:
  workflow_dispatch:
  schedule:
    - cron: '40 2 6 * *'  # Runs at 02:40, on day 6 of the month
  push:
    branches:
      - main
    paths:
      - 'base-docker-arm/**'

permissions:
  contents: read
  packages: write
  # id-token: write
  # attestations: write

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    with:
      path: base-docker-arm
      tag: base-docker-arm
      runner: ubuntu-24.04-arm
