name: misc-arm
on:
  workflow_dispatch:
  schedule:
    - cron: '50 2 6 * *'  # Runs at 02:50, on day 6 of the month
  pull_request:
    branches:
      - main
    paths:
      - 'base-docker-arm/**'
  push:
    branches:
      - main
    paths:
      - 'misc-arm/**'

permissions:
  contents: read
  packages: write
  # id-token: write
  # attestations: write

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    with:
      path: misc-arm
      tag: misc-arm
      runner: ubuntu-24.04-arm
